name: "publish-deb"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build deb package
        run: ./create-deb.sh

      - name: Publish deb package
        run: |
          curl \
            --user your_username:your_password_or_token \
            --upload-file target/debian/*.deb \
            https://git.pvv.ntnu.no/api/packages/testuser/debian/pool/bionic/main/upload
